# -*- coding: utf-8 -*-
"""
/***************************************************************************
 HDSRTool
                                 A QGIS plugin
 HDSR tool voor grondonderzoek interpretatie
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-02-15
        copyright            : (C) 2022 by Breinbaas | Rob van Putten
        email                : breinbaasnl@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load HDSRTool class from file HDSRTool.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .hdsr_tool import HDSRTool
    return HDSRTool(iface)
